# Default values for superflex-mapp-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
 
replicaCount: 2

serviceName: "my-serviceName"

consul:
  enabled: true
  host: "consul-serviceName.namespace.svc"
  port: "8500"
  security:
    enabled: false
    aclToken: "acltoken"

image:
  repository: harbor.eks.glic-solutions.com/glic/superflex-mapp-gateway
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: registry-secret
nameOverride: ""
fullnameOverride: ""

ports:
  - name: app
    containerPort: 8090
    protocol: TCP
  - name: hazelcast
    containerPort: 5701
    protocol: TCP

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "k8s,production,sleuth"
  - name: SPRING_CONFIG_LOCATION
    value: "classpath:/,file:conf/"
  - name: POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8090

# Port should be between 30000-32767
nodePort:
  enabled: false
  port: 30057

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 0.75
    memory: 768Mi
  requests:
    cpu: 0.3
    memory: 256Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
  #  cpu: 250m
  #  memory: 2048Mi
  #requests:
  #  cpu: 100m
  #  memory: 1024Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

rancherLogging:
  enabled: false
  elk:
    host: "elk-serviceName.namespace.svc"
    port: "9200"
    user: "admin"
    secret: "password"

tokens: c8a63536,bc08,4e37,9adf,36e3f203ab6d
